# Milestone 1, Phase 1 (Inference Notebook)

In [1]:
import pandas as pd
import numpy as np
import joblib

In [74]:
with open('minmax_scaler.pkl', 'rb') as file_1:
  scaler = joblib.load(file_1)
  
with open('gaussian.pkl', 'rb') as file_2:
  gaussian_best = joblib.load(file_2)
  
with open('num_col.pkl', 'rb') as file_3:
  num_col = joblib.load(file_3)
  
with open('cat_col.pkl', 'rb') as file_4:
  cat_col = joblib.load(file_4)

In [85]:
pay_0 = [0,0,2,0,0,1,2,0,0,0]
pay_2 = [4,0,1,2,4,0,0,0,0,0]
pay_3 = [0,0,0,0,0,1,2,3,1,2]
pay_4 = [1,1,1,0,0,0,0,1,2,3]
pay_5 = [0,0,1,2,3,0,0,0,0,0]
pay_6 = [1,1,0,0,0,0,0,1,1,2]

np.random.seed(10) 
limit_balance = np.random.choice(np.arange(10000,800000,10000), size=10)

data_inf = pd.DataFrame({'limit_balance':limit_balance, 'pay_0':pay_0, 'pay_2':pay_2, 'pay_3':pay_3, 'pay_4':pay_4, 'pay_5':pay_5, 'pay_6':pay_6})
data_inf

   limit_balance  pay_0  pay_2  pay_3  pay_4  pay_5  pay_6
0         100000      0      4      0      1      0      1
1         160000      0      0      0      1      0      1
2         650000      2      1      0      1      1      0
3         290000      0      2      0      0      2      0
4         300000      0      4      0      0      3      0
5          90000      1      0      1      0      0      0
6         740000      2      0      2      0      0      0
7          10000      0      0      3      1      0      1
8         410000      0      0      1      2      0      1
9         370000      0      0      2      3      0      2

In [86]:
data_inf_scaled = scaler.transform(data_inf[num_col])

In [87]:
data_inf_final = np.concatenate([data_inf_scaled, data_inf[cat_col]], axis=1)

In [88]:
data_inf['GaussianNB Predict'] = gaussian_best.predict(data_inf_final)
data_inf

   limit_balance  pay_0  pay_2  pay_3  pay_4  pay_5  pay_6  GaussianNB Predict
0         100000      0      4      0      1      0      1                   1
1         160000      0      0      0      1      0      1                   0
2         650000      2      1      0      1      1      0                   0
3         290000      0      2      0      0      2      0                   1
4         300000      0      4      0      0      3      0                   1
5          90000      1      0      1      0      0      0                   0
6         740000      2      0      2      0      0      0                   0
7          10000      0      0      3      1      0      1                   1
8         410000      0      0      1      2      0      1                   0
9         370000      0      0      2      3      0      2                   1